"""
Generates Terminology Database v2 (Task 11 / Milestone 6).

Expands deep_learning.json, computer_science.json, mathematics.json to >=150 terms each,
with 'term', 'hindi', 'aliases', and 'protected' flags.
"""

import json
from pathlib import Path

TERMINOLOGY_DIR = Path("data/terminology")
TERMINOLOGY_DIR.mkdir(parents=True, exist_ok=True)

# 1. DEEP LEARNING (>= 150 terms)
DL_TERMS = [
    # Core Architecture & Components
    ("attention", "अटेंशन / ध्यान", ["attention mechanism", "self-attention"], True),
    ("transformer", "ट्रांसफार्मर", ["transformers", "transformer architecture"], True),
    ("backpropagation", "बैकप्रोपेगेशन / पश्च-प्रसार", ["backprop", "bp"], True),
    ("gradient", "ग्रेडिएंट / ढाल", ["gradients", "gradient vector"], False),
    ("embedding", "एम्बेडिंग / संसेचन", ["embeddings", "word embeddings"], False),
    ("tokenizer", "टोकनाइज़र", ["tokenization", "subword tokenizer"], False),
    ("activation", "सक्रियण", ["activation function", "non-linearity"], False),
    ("dropout", "ड्रॉपआउट", ["dropout layer", "inverted dropout"], True),
    ("convolution", "कन्वोल्यूशन / संवलन", ["conv2d", "convolutional layer"], False),
    ("epoch", "युग / चक्र", ["epochs", "training epoch"], False),
    ("overfitting", "अति-अनुकूलन / ओवरफिटिंग", ["overfit", "model overfitting"], False),
    ("regularization", "नियमितीकरण", ["l1 regularization", "l2 regularization"], False),
    ("softmax", "सॉफ्टमैक्स", ["softmax layer", "softmax activation"], True),
    ("perceptron", "परसेप्ट्रॉन", ["multilayer perceptron", "mlp"], True),
    ("optimizer", "ऑप्टिमाइज़र / अनुकूलक", ["adam optimizer", "optimization algorithm"], False),
    ("hyperparameter", "हाइपरपैरामीटर", ["hyperparameters", "hparams"], False),
    ("autograd", "ऑटोग्रेड", ["automatic differentiation", "autodiff"], True),
    ("normalization", "सामान्यीकरण", ["batch norm", "layer norm"], False),
    ("residual", "अवशिष्ट / रेजिडुअल", ["residual connection", "skip connection"], True),
    ("latent", "अव्यक्त / लेटेंट", ["latent space", "latent representation"], False),
    ("recurrent", "आवर्ती", ["rnn", "recurrent neural network"], True),
    ("feedforward", "अग्रगामी / फीडफॉरवर्ड", ["ffn", "feedforward network"], True),
    ("autoencoder", "ऑटोएनकोडर", ["vae", "variational autoencoder"], True),
    ("perplexity", "पर्प्लेक्सिटी / संशय", ["ppl", "language model perplexity"], False),
    ("inference", "अनुमान / इन्फेरेंस", ["model inference", "serving"], False),
    ("checkpoint", "चेकपॉइंट", ["model checkpoint", "weights checkpoint"], False),
    ("quantization", "क्वांटाइजेशन / परिमाणीकरण", ["int8 quantization", "weight quantization"], True),
    ("logits", "लॉगिट्स", ["raw logits", "unnormalized log probabilities"], False),
    ("encoder", "एनकोडर / संकेतक", ["encoder block", "feature encoder"], True),
    ("decoder", "डिकोडर / विसंकेतक", ["decoder block", "autoregressive decoder"], True),
    ("finetuning", "फाइन-ट्यूनिंग", ["fine-tuning", "parameter fine-tuning"], False),
    ("cross-entropy", "क्रॉस-एन्ट्रॉपी", ["categorical cross entropy", "xent"], True),
    ("generalization", "सामान्यीकरण", ["generalization gap", "out-of-distribution generalization"], False),
    ("tensor", "टेंसर", ["multidimensional array", "tensors"], True),
    ("gradient-descent", "ग्रेडिएंट डिसेंट", ["sgd", "stochastic gradient descent"], True),
    ("loss-function", "हानि फलन", ["objective function", "cost function"], False),
    ("learning-rate", "सीखने की दर", ["lr", "step size"], False),
    ("batch-size", "बैच का आकार", ["minibatch size", "batch size"], False),
    ("momentum", "संवेग / मोमेंटम", ["nesterov momentum", "gradient momentum"], False),
    ("relu", "रेलू", ["rectified linear unit", "relu activation"], True),
    ("gelu", "गेलू", ["gaussian error linear unit", "gelu activation"], True),
    ("sigmoid", "सिग्मॉइड", ["sigmoid function", "logistic sigmoid"], True),
    ("tanh", "टेनएच", ["hyperbolic tangent", "tanh activation"], True),
    ("weight-decay", "वेट डिके", ["l2 penalty", "parameter shrinkage"], False),
    ("early-stopping", "पूर्व समाप्ति", ["early stop", "early stopping criterion"], False),
    ("data-augmentation", "डेटा संवर्धन", ["image augmentation", "data augmentations"], False),
    ("adversarial", "प्रतिकूल / एडवरसैरियल", ["adversarial attack", "adversarial training"], False),
    ("gan", "गैन", ["generative adversarial network", "gans"], True),
    ("diffusion", "डिफ्यूजन / विसरण", ["diffusion models", "ddpm"], True),
    ("lora", "लोरा", ["low-rank adaptation", "lora fine-tuning"], True),
    ("qlora", "क्यूपी-लोरा", ["quantized lora", "4-bit lora"], True),
    ("peft", "पेफ्ट", ["parameter-efficient fine-tuning", "peft library"], True),
    ("rope", "रोप", ["rotary position embedding", "rotary positional embeddings"], True),
    ("flashattention", "फ्लैश-अटेंशन", ["flash attention 2", "flash-attn"], True),
    ("dpo", "डीपीओ", ["direct preference optimization", "dpo training"], True),
    ("rlhf", "आरएलएचएफ", ["reinforcement learning from human feedback", "rlhf alignment"], True),
    ("ppo", "पीपीओ", ["proximal policy optimization", "ppo algorithm"], True),
    ("beam-search", "बीम सर्च", ["beam decoding", "beam width"], False),
    ("temperature", "तापमान / टेम्परेचर", ["sampling temperature", "temperature parameter"], False),
    ("top-k", "टॉप-के", ["top-k sampling", "top k filtering"], False),
    ("top-p", "टॉप-पी", ["nucleus sampling", "top-p sampling"], False),
    ("rag", "रैग", ["retrieval-augmented generation", "rag pipeline"], True),
    ("vector-database", "वेक्टर डेटाबेस", ["vector store", "vector db"], False),
    ("cosine-similarity", "कोसाइन समानता", ["cosine distance", "cos similarity"], False),
    ("dot-product", "डॉट उत्पाद", ["inner product", "scalar product"], False),
    ("contrastive", "विरोधाभासी / कंट्रास्टिव", ["contrastive loss", "contrastive learning"], False),
    ("siamese-network", "सिएमीज नेटवर्क", ["siamese twin network", "dual encoder"], True),
    ("clip", "क्लिप", ["contrastive language-image pretraining", "clip model"], True),
    ("bert", "बर्ट", ["bidirectional encoder representations", "bert model"], True),
    ("gpt", "जीपीटी", ["generative pretrained transformer", "gpt model"], True),
    ("t5", "टी5", ["text-to-text transfer transformer", "t5 encoder-decoder"], True),
    ("llama", "लामा", ["llama architecture", "open llama"], True),
    ("mistral", "मिस्ट्रल", ["mistral architecture", "mistral 7b"], True),
    ("mixtral", "मिक्सट्रल", ["sparse mixture of experts", "moe"], True),
    ("expert", "विशेषज्ञ / एक्सपर्ट", ["mixture of experts", "routing network"], False),
    ("gating", "गेटिंग", ["gating network", "router"], False),
    ("context-window", "संदर्भ विंडो", ["context length", "max tokens"], False),
    ("self-supervised", "स्व-पर्यवेक्षित", ["self-supervised learning", "ssl"], False),
    ("semi-supervised", "अर्ध-पर्यवेक्षित", ["semi-supervised training", "pseudo-labeling"], False),
    ("unsupervised", "अपर्यवेक्षित", ["unsupervised learning", "clustering"], False),
    ("supervised", "पर्यवेक्षित", ["supervised learning", "labeled data"], False),
    ("zero-shot", "शून्य-शॉट", ["zero-shot inference", "zero-shot learning"], False),
    ("few-shot", "फ्यू-शॉट", ["few-shot in-context learning", "few-shot prompting"], False),
    ("in-context-learning", "संदर्भ में सीखना", ["icl", "prompt learning"], False),
    ("chain-of-thought", "विचारों की श्रृंखला", ["cot", "cot prompting"], False),
    ("hallucination", "मतिभ्रम / हैलुसिनेशन", ["model hallucination", "factual inaccuracies"], False),
    ("grounding", "आधार / ग्राउंडिंग", ["factual grounding", "grounded generation"], False),
    ("alignment", "संरेखण / अलाइनमेंट", ["ai alignment", "preference alignment"], False),
    ("pruning", "छंटाई / प्रूनिंग", ["model pruning", "structured pruning"], True),
    ("distillation", "आसवन / डिस्टिलेशन", ["knowledge distillation", "teacher-student model"], True),
    ("teacher-student", "शिक्षक-छात्र", ["teacher model", "student network"], False),
    ("fp16", "एफपी16", ["half precision", "16-bit float"], True),
    ("bf16", "बीएफ16", ["bfloat16", "brain floating point"], True),
    ("fp32", "एफपी32", ["single precision", "32-bit float"], True),
    ("int8", "इंट8", ["8-bit integer", "int8 quantization"], True),
    ("int4", "इंट4", ["4-bit integer", "awq", "gptq"], True),
    ("backprop-through-time", "समय के माध्यम से बैकप्रॉप", ["bptt", "recurrent backprop"], True),
    ("gru", "जीआरयू", ["gated recurrent unit", "gru cell"], True),
    ("lstm", "एलएसटीएम", ["long short-term memory", "lstm network"], True),
    ("vanishing-gradient", "लुप्तप्राय ग्रेडिएंट", ["vanishing gradient problem", "gradient vanishing"], False),
    ("exploding-gradient", "विस्फोटक ग्रेडिएंट", ["exploding gradient problem", "gradient explosion"], False),
    ("gradient-clipping", "ग्रेडिएंट क्लिपिंग", ["clip gradients", "norm clipping"], False),
    ("warmup", "वार्मअप", ["learning rate warmup", "linear warmup"], False),
    ("cosine-decay", "कोसाइन क्षय", ["cosine annealing", "cosine schedule"], False),
    ("mini-batch", "मिनी-बैच", ["minibatch", "batch stochastic gradient descent"], False),
    ("epoch-loss", "युग हानि", ["training loss", "epoch metric"], False),
    ("validation-loss", "सत्यापन हानि", ["val loss", "validation error"], False),
    ("test-accuracy", "परीक्षण सटीकता", ["test acc", "generalization score"], False),
    ("auc-roc", "एयूसी-आरओसी", ["area under the curve", "roc curve"], True),
    ("precision", "सटीकता / प्रिसिजन", ["positive predictive value", "precision score"], False),
    ("recall", "पुनरावलोकन / रिकॉल", ["true positive rate", "sensitivity"], False),
    ("f1-score", "एफ1-स्कोर", ["f-measure", "harmonic mean precision recall"], True),
    ("confusion-matrix", "भ्रम आव्यूह", ["error matrix", "classification contingency table"], False),
    ("bpe", "बीपीई", ["byte-pair encoding", "bpe tokenizer"], True),
    ("wordpiece", "वर्डपीस", ["wordpiece tokenization", "subword algorithm"], True),
    ("unigram-tokenizer", "यूनिग्राम टोकनाइज़र", ["sentencepiece unigram", "spm"], True),
    ("sentencepiece", "सेंटेंसपीस", ["sentencepiece library", "spm model"], True),
    ("multi-head", "मल्टी-हेड", ["multihead self-attention", "mha"], True),
    ("multi-query", "मल्टी-क्वेरी", ["multi-query attention", "mqa"], True),
    ("grouped-query", "समूह-क्वेरी", ["grouped-query attention", "gqa"], True),
    ("kv-cache", "केवी-कैश", ["key-value cache", "paged attention"], True),
    ("vllm", "वीएलएलएम", ["vllm serving", "paged attention framework"], True),
    ("speculative-decoding", "सट्टा डिकोडिंग", ["draft model decoding", "assisted generation"], False),
    ("continuous-batching", "निरंतर बैचिंग", ["dynamic batching", "iteration-level scheduling"], False),
    ("cuda", "कूडा", ["nvidia cuda", "cuda kernel"], True),
    ("triton", "ट्राइटन", ["openai triton", "triton language"], True),
    ("gpu-memory", "जीपीयू मेमोरी", ["vram", "device memory"], False),
    ("distributed-training", "वितरित प्रशिक्षण", ["ddp", "fsdp", "deepspeed"], False),
    ("tensor-parallelism", "टेंसर समानांतरता", ["tp", "megatron-lm"], True),
    ("pipeline-parallelism", "पाइपलाइन समानांतरता", ["pp", "piped training"], True),
    ("data-parallelism", "डेटा समानांतरता", ["ddp", "distributed data parallel"], True),
    ("fsdp", "एफएसडीपी", ["fully sharded data parallel", "zero-3"], True),
    ("deepspeed", "डीपस्पीड", ["microsoft deepspeed", "zero optimizer"], True),
    ("cross-validation", "क्रॉस-सत्यापन", ["k-fold cross validation", "stratified k-fold"], False),
    ("underfitting", "अल्प-अनुकूलन / अंडरफिटिंग", ["high bias", "underfit model"], False),
    ("inductive-bias", "आगमनात्मक पूर्वाग्रह", ["architectural prior", "translational invariance"], False),
    ("pooling", "पूलिंग", ["max pooling", "average pooling"], False),
    ("stride", "स्ट्राइड", ["convolution stride", "filter step"], False),
    ("dilation", "विस्तारण / डाइलेशन", ["dilated convolution", "atrous convolution"], False),
    ("receptive-field", "ग्रहणशील क्षेत्र", ["effective receptive field", "rf"], False),
    ("skip-gram", "स्किप-ग्राम", ["skipgram model", "word2vec skipgram"], True),
    ("cbow", "सीबो", ["continuous bag of words", "word2vec cbow"], True),
    ("glove", "ग्लोव", ["global vectors for word representation", "glove embeddings"], True),
    ("fasttext", "फास्टटेक्स्ट", ["subword embeddings", "facebook fasttext"], True),
    ("weight-initialization", "भार आरंभीकरण", ["xavier init", "he initialization"], False),
    ("gradient-accumulation", "ग्रेडिएंट संचय", ["accumulate gradients", "grad accum"], False),
    ("mixed-precision", "मिश्रित परिशुद्धता", ["amp", "automatic mixed precision"], True),
    ("loss-landscape", "हानि परिदृश्य", ["optimization landscape", "flat minima"], False),
    ("saddle-point", "सैडल बिंदु", ["saddle points", "non-convex optimization"], False),
    ("gradient-flow", "ग्रेडिएंट प्रवाह", ["gradient dynamics", "information flow"], False),
    ("activation-map", "सक्रियण मानचित्र", ["feature heatmap", "cam"], False),
    ("positional-encoding", "स्थितीय एन्कोडिंग", ["sinusoidal positional encoding", "absolute position"], True),
]

# 2. COMPUTER SCIENCE (>= 150 terms)
CS_TERMS = [
    ("algorithm", "एल्गोरिदम / कलन विधि", ["algorithms", "computational procedure"], True),
    ("recursion", "पुनरावृत्ति / रिकर्शन", ["recursive call", "recursion base case"], True),
    ("heap", "हीप", ["min-heap", "max-heap", "binary heap"], True),
    ("stack", "स्टैक", ["call stack", "lifo structure"], True),
    ("queue", "कतार / क्यू", ["priority queue", "fifo structure"], True),
    ("pointer", "पॉइंटर / सूचक", ["raw pointer", "memory pointer", "smart pointer"], True),
    ("compiler", "कंपाइलर", ["code compiler", "optimizing compiler"], True),
    ("database", "डेटाबेस", ["relational database", "rdbms", "nosql"], True),
    ("deadlock", "डेडलॉक", ["circular wait deadlock", "resource deadlock"], True),
    ("thread", "थ्रेड", ["worker thread", "concurrent thread"], True),
    ("hashtable", "हैश टेबल", ["hash map", "hash dictionary"], True),
    ("polymorphism", "बहुरूपता / पॉलीमॉर्फिज्म", ["dynamic polymorphism", "method overriding"], True),
    ("inheritance", "विरासत / इनहेरिटेंस", ["class inheritance", "subtyping"], True),
    ("bytecode", "बाइटकोड", ["jvm bytecode", "python bytecode"], True),
    ("binary-tree", "बाइनरी ट्री", ["binary search tree", "bst"], True),
    ("avl-tree", "एवीएल ट्री", ["self-balancing tree", "avl balanced bst"], True),
    ("red-black-tree", "रेड-ब्लैक ट्री", ["rbtree", "balanced binary tree"], True),
    ("b-tree", "बी-ट्री", ["b-plus tree", "database index tree"], True),
    ("trie", "ट्राई", ["prefix tree", "radix tree"], True),
    ("graph", "ग्राफ", ["directed graph", "undirected graph"], True),
    ("adjacency-list", "संलग्नता सूची", ["adj list", "graph representation"], False),
    ("adjacency-matrix", "संलग्नता आव्यूह", ["adj matrix", "graph matrix"], False),
    ("depth-first-search", "गहराई-प्रथम खोज", ["dfs", "depth first traversal"], True),
    ("breadth-first-search", "चौड़ाई-प्रथम खोज", ["bfs", "breadth first traversal"], True),
    ("dijkstra", "डिजक्स्ट्रा", ["dijkstra algorithm", "shortest path"], True),
    ("bellman-ford", "बेलमैन-फोर्ड", ["bellman ford algorithm", "negative edge shortest path"], True),
    ("floyd-warshall", "फ्लोयड-मार्शल", ["all-pairs shortest path", "floyd warshall algorithm"], True),
    ("kruskal", "क्रुस्कल", ["kruskal algorithm", "minimum spanning tree"], True),
    ("prim", "प्रिम", ["prim algorithm", "mst algorithm"], True),
    ("topological-sort", "टोपोलॉजिकल सॉर्ट", ["topo sort", "dag ordering"], True),
    ("dynamic-programming", "डायनामिक प्रोग्रामिंग", ["dp", "memoization", "tabulation"], True),
    ("memoization", "मेमोइजेशन", ["cached computation", "memoized function"], True),
    ("greedy-algorithm", "लालची एल्गोरिदम", ["greedy heuristic", "local optimal choice"], False),
    ("divide-and-conquer", "विभाजित करो और जीतो", ["divide and conquer approach", "d&c"], False),
    ("quicksort", "क्विकसॉर्ट", ["quick sort", "pivot partitioning"], True),
    ("mergesort", "मर्जसॉर्ट", ["merge sort", "stable sort"], True),
    ("heapsort", "हीपसॉर्ट", ["heap sort", "in-place heap sorting"], True),
    ("bubble-sort", "बबल सॉर्ट", ["bubble sorting algorithm", "sinking sort"], False),
    ("insertion-sort", "प्रविष्टि सॉर्ट", ["insertion sorting", "online sorting"], False),
    ("binary-search", "बाइनरी सर्च", ["dichotomic search", "half-interval search"], True),
    ("asymptotic", "अनंतस्पर्शी / असम्टोटिक", ["big-o", "big-theta", "big-omega"], True),
    ("big-o", "बिग-ओ", ["big o notation", "order of growth"], True),
    ("time-complexity", "समय जटिलता", ["computational time complexity", "worst-case time"], False),
    ("space-complexity", "स्थान जटिलता", ["memory complexity", "auxiliary space"], False),
    ("np-complete", "एनपी-पूर्ण", ["np-completeness", "cook-levin theorem"], True),
    ("np-hard", "एनपी-कठिन", ["np-hardness", "reduction"], True),
    ("turing-machine", "ट्यूरिंग मशीन", ["universal turing machine", "utm"], True),
    ("halting-problem", "हल्टिंग समस्या", ["undecidable problem", "turing halting"], True),
    ("automata", "ऑटोमेटा", ["finite automata", "dfa", "nfa"], True),
    ("context-free-grammar", "संदर्भ-मुक्त व्याकरण", ["cfg", "pushdown automata"], True),
    ("regular-expression", "रेगुलर एक्सप्रेशन", ["regex", "regexp"], True),
    ("operating-system", "ऑपरेटिंग सिस्टम", ["os", "kernel"], True),
    ("kernel", "कर्नेल", ["monolithic kernel", "microkernel"], True),
    ("virtual-memory", "वर्चुअल मेमोरी", ["paging", "swap memory"], True),
    ("paging", "पेजिंग", ["page table", "page fault"], True),
    ("tlb", "टीएलबी", ["translation lookaside buffer", "mmu cache"], True),
    ("context-switch", "संदर्भ स्विच", ["process switch", "thread context switch"], False),
    ("process", "प्रक्रिया / प्रोसेस", ["os process", "process control block", "pcb"], False),
    ("multiprocessing", "मल्टीप्रोसेसिंग", ["parallel processing", "forking"], False),
    ("multithreading", "मल्टीथ्रेडिंग", ["concurrent threads", "thread pool"], False),
    ("mutex", "म्यूटेक्स", ["mutual exclusion", "binary lock"], True),
    ("semaphore", "सेमाफोर", ["counting semaphore", "signaling mechanism"], True),
    ("race-condition", "रेस स्थिति", ["data race", "concurrency bug"], False),
    ("critical-section", "महत्वपूर्ण खंड", ["synchronized block", "protected region"], False),
    ("atomic-operation", "परमाणु संक्रिया / एटॉमिक", ["atomicity", "compare-and-swap", "cas"], True),
    ("deadlock-prevention", "डेडलॉक रोकथाम", ["banker's algorithm", "resource ordering"], False),
    ("scheduling", "शेड्यूलिंग", ["cpu scheduling", "round-robin", "sjf"], False),
    ("round-robin", "राउंड रॉबिन", ["rr scheduling", "time-sliced scheduling"], True),
    ("file-system", "फाइल सिस्टम", ["fs", "ext4", "ntfs", "zfs"], False),
    ("inode", "आईनोड", ["inode table", "file metadata pointer"], True),
    ("tcp", "टीसीपी", ["transmission control protocol", "tcp handshake"], True),
    ("udp", "यूडीपी", ["user datagram protocol", "connectionless socket"], True),
    ("ip-address", "आईपी पता", ["ipv4", "ipv6", "internet protocol"], True),
    ("dns", "डीएनएस", ["domain name system", "dns resolver"], True),
    ("http", "एचटीटीपी", ["hypertext transfer protocol", "http/2", "http/3"], True),
    ("https", "एचटीटीपीएस", ["secure http", "tls/ssl"], True),
    ("tls", "टीएलएस", ["transport layer security", "ssl certificate"], True),
    ("socket", "सॉकेट", ["network socket", "berkeley socket"], False),
    ("packet", "पैकेट", ["network packet", "ip packet"], False),
    ("router", "राउटर", ["routing table", "network router"], False),
    ("firewall", "फ़ायरवॉल", ["network packet filter", "security gateway"], False),
    ("load-balancer", "लोड बैलेंसर", ["reverse proxy load balancer", "haproxy"], False),
    ("api", "एपीआई", ["application programming interface", "rest api"], True),
    ("rest", "रेस्ट", ["representational state transfer", "restful service"], True),
    ("graphql", "ग्राफक्यूएल", ["graphql query", "graphql schema"], True),
    ("rpc", "आरपीसी", ["remote procedure call", "grpc"], True),
    ("grpc", "जीआरपीसी", ["google remote procedure call", "protobuf"], True),
    ("protobuf", "प्रोटोबफ़", ["protocol buffers", "serialization protocol"], True),
    ("json", "जेसन", ["javascript object notation", "json document"], True),
    ("xml", "एक्सएमएल", ["extensible markup language", "xml parser"], True),
    ("sql", "एसक्यूएल", ["structured query language", "relational query"], True),
    ("nosql", "नोएसक्यूएल", ["document database", "key-value store"], True),
    ("acid", "एसिड", ["atomicity consistency isolation durability", "acid transactions"], True),
    ("cap-theorem", "सीएपी प्रमेय", ["brewer cap theorem", "consistency availability partition"], True),
    ("sharding", "शार्डिंग", ["database sharding", "horizontal partitioning"], True),
    ("replication", "प्रतिकृति / प्रतिकृतिकरण", ["primary-replica", "master-slave"], False),
    ("distributed-systems", "वितरित प्रणालियां", ["distributed computing", "consensus"], False),
    ("consensus", "आम सहमति / सर्वसम्मति", ["distributed consensus", "byzantine fault"], False),
    ("paxos", "पैक्सोस", ["paxos consensus algorithm", "multi-paxos"], True),
    ("raft", "राफ्ट", ["raft consensus protocol", "leader election"], True),
    ("cache", "कैश", ["memory cache", "redis", "memcached"], True),
    ("lru-cache", "एलआरयू कैश", ["least recently used cache", "cache eviction"], True),
    ("redis", "रेडिस", ["in-memory data store", "redis key-value"], True),
    ("docker", "डॉकर", ["container engine", "docker container"], True),
    ("container", "कंटेनर", ["os virtualization", "container image"], False),
    ("kubernetes", "कुबेरनेट्स", ["k8s", "container orchestration"], True),
    ("microservices", "माइक्रोसर्विसेज", ["microservice architecture", "decoupled services"], False),
    ("monolith", "मोनोलिथ", ["monolithic application", "single deployment unit"], False),
    ("ci-cd", "सीआई-सीडी", ["continuous integration continuous deployment", "pipeline automation"], True),
    ("git", "गिट", ["distributed version control", "git commit"], True),
    ("garbage-collection", "कचरा संग्रह / गार्बेज कलेक्शन", ["gc", "memory reclamation"], True),
    ("memory-leak", "मेमोरी रिसाव", ["unreleased heap memory", "dangling allocation"], False),
    ("buffer-overflow", "बफर ओवरफ्लो", ["stack overflow", "memory corruption"], False),
    ("sql-injection", "एसक्यूएल इंजेक्शन", ["sqli", "database exploitation"], True),
    ("xss", "एक्सएसएस", ["cross-site scripting", "client-side injection"], True),
    ("csrf", "सीएसआरएफ", ["cross-site request forgery", "session hijacking"], True),
    ("cryptography", "क्रिप्टोग्राफी / गूढ़लेखन", ["encryption", "decryption"], False),
    ("symmetric-key", "सममित कुंजी", ["aes", "block cipher"], False),
    ("asymmetric-key", "असममित कुंजी", ["rsa", "public key cryptography"], False),
    ("rsa", "आरएसए", ["rsa algorithm", "public-key cryptosystem"], True),
    ("aes", "एईएस", ["advanced encryption standard", "symmetric cipher"], True),
    ("hash-function", "हैश फलन", ["sha-256", "cryptographic hash"], False),
    ("digital-signature", "डिजिटल हस्ताक्षर", ["signature verification", "asymmetric signature"], False),
    ("parser", "पार्सर", ["syntax parser", "ast generator"], True),
    ("lexer", "लेक्सर", ["lexical analyzer", "scanner"], True),
    ("ast", "एएसटी", ["abstract syntax tree", "parse tree"], True),
    ("interpreter", "दुभाषिया / इंटरप्रेटर", ["code interpreter", "runtime evaluation"], True),
    ("jit-compiler", "जिट कंपाइलर", ["just-in-time compilation", "jit execution"], True),
    ("refactoring", "रीफैक्टरिंग", ["code refactoring", "clean code"], False),
    ("design-pattern", "डिजाइन पैटर्न", ["gang of four", "software pattern"], False),
    ("singleton", "सिंगलटन", ["singleton pattern", "single instance"], True),
    ("factory-pattern", "फैक्ट्री पैटर्न", ["factory method", "abstract factory"], True),
    ("observer-pattern", "पर्यवेक्षक पैटर्न", ["publish-subscribe", "event listener"], True),
    ("unit-testing", "यूनिट परीक्षण", ["unit tests", "pytest", "junit"], False),
    ("integration-testing", "एकीकरण परीक्षण", ["system test", "end-to-end testing"], False),
    ("mocking", "मॉकिंग", ["test mock", "stubbing"], False),
    ("profiler", "प्रोफाइलर", ["performance profiler", "cpu profiler"], False),
    ("benchmarking", "बेंचमार्किंग", ["runtime performance benchmark", "load testing"], False),
    ("cloud-computing", "क्लाउड कंप्यूटिंग", ["aws", "gcp", "azure"], False),
    ("serverless", "सर्वरलेस", ["aws lambda", "cloud functions"], False),
    ("virtualization", "वर्चुअलाइजेशन", ["hypervisor", "virtual machine", "vm"], False),
    ("hypervisor", "हाइपरवाइजर", ["type 1 hypervisor", "type 2 hypervisor"], True),
    ("big-data", "बड़ा डेटा / बिग डेटा", ["hadoop", "spark", "mapreduce"], False),
    ("mapreduce", "मैपरिड्यूस", ["map and reduce distributed processing", "hadoop mapreduce"], True),
    ("spark", "स्पार्क", ["apache spark", "in-memory distributed compute"], True),
    ("kafka", "काफ्का", ["apache kafka", "event stream processing"], True),
    ("event-loop", "इवेंट लूप", ["async event loop", "non-blocking io"], True),
    ("callback", "कॉलबैक", ["callback function", "promise callback"], False),
    ("coroutine", "कोरूटीन", ["async await coroutine", "green thread"], True),
    ("serialization", "क्रमांकन / सीरियलाइजेशन", ["data serialization", "marshaling"], False),
    ("deserialization", "विसंकेतन / डीसीरियलाइजेशन", ["unmarshaling", "json parse"], False),
    ("thread-pool", "थ्रेड पूल", ["worker thread pool", "executor service"], True),
]

# 3. MATHEMATICS (>= 150 terms)
MATH_TERMS = [
    ("derivative", "व्युत्पन्न / अवकलज", ["differentiation", "rate of change"], True),
    ("integral", "समाकलन", ["integration", "definite integral", "indefinite integral"], True),
    ("eigenvector", "आइगेनवेक्टर / विशेषता सदिश", ["characteristic vector", "eigenvalue eigenvector"], True),
    ("determinant", "सारणिक / डिटर्मिनेंट", ["matrix determinant", "det(A)"], True),
    ("polynomial", "बहुपद", ["polynomial function", "degree of polynomial"], False),
    ("matrix", "आव्यूह / मैट्रिक्स", ["matrices", "matrix algebra"], True),
    ("theorem", "प्रमेय", ["mathematical theorem", "lemma"], False),
    ("inequality", "असमानता / असमिका", ["cauchy-schwarz inequality", "triangle inequality"], False),
    ("differentiable", "विभेदनीय / अवकलनीय", ["differentiability", "smooth function"], False),
    ("probability", "प्रायिकता / संभावना", ["probability theory", "random variable"], False),
    ("variance", "विचरण / वेरिएंस", ["sigma squared", "statistical variance"], False),
    ("logarithm", "लघुगणक", ["log", "natural logarithm", "ln"], False),
    ("eigenvalue", "आइगेनवेल्यू / विशेषता मान", ["characteristic value", "lambda"], True),
    ("linear-algebra", "रैखिक बीजगणित", ["vector algebra", "matrix operations"], True),
    ("vector-space", "सदिश अंतरिक्ष", ["linear space", "hilbert space", "banach space"], True),
    ("subspace", "उप-अंतरिक्ष", ["linear subspace", "vector subspace"], False),
    ("basis", "आधार / बेसिस", ["orthonormal basis", "coordinate basis"], True),
    ("dimension", "विमा / आयाम", ["vector space dimension", "degrees of freedom"], False),
    ("linear-transformation", "रैखिक रूपांतरण", ["linear map", "linear operator"], True),
    ("kernel-space", "कर्नेल अंतरिक्ष / नल स्पेस", ["null space", "nullity"], True),
    ("rank", "रैंक / कोटि", ["matrix rank", "rank-nullity theorem"], True),
    ("inversion", "व्युत्क्रमण", ["matrix inverse", "invertible matrix"], False),
    ("orthogonal", "लांबिक / ऑर्थोगोनल", ["orthogonality", "perpendicular vectors"], True),
    ("orthonormal", "लांबिक सामान्यीकृत", ["orthonormality", "unit orthogonal vector"], True),
    ("gram-schmidt", "ग्राम-श्मिट", ["gram schmidt orthogonalization", "basis construction"], True),
    ("svd", "एसवीडी", ["singular value decomposition", "matrix factorization"], True),
    ("qr-factorization", "क्यूआर गुणनखंडन", ["qr decomposition", "gram-schmidt qr"], True),
    ("lu-decomposition", "एल्यू अपघटन", ["lower upper factorization", "gaussian elimination"], True),
    ("cholesky", "चोलेस्की", ["cholesky decomposition", "positive definite matrix"], True),
    ("positive-definite", "धनात्मक निश्चित", ["positive semi-definite", "spd matrix"], True),
    ("inner-product", "आंतरिक उत्पाद", ["dot product", "scalar product"], False),
    ("norm", "मानदंड / नॉर्म", ["l1 norm", "l2 norm", "frobenius norm"], False),
    ("cauchy-schwarz", "कॉची-श्वार्ज", ["cauchy-schwarz inequality", "inner product bound"], True),
    ("limit", "सीमा / लिमिट", ["mathematical limit", "epsilon-delta definition"], False),
    ("continuity", "निरंतरता / सांतत्य", ["continuous function", "uniform continuity"], False),
    ("infinitesimal", "अनंतसूक्ष्म", ["infinitesimal calculus", "differential element"], False),
    ("partial-derivative", "आंशिक अवकलज", ["partial differentiation", "del operator"], True),
    ("gradient-vector", "ग्रेडिएंट सदिश", ["del f", "spatial gradient"], True),
    ("divergence", "अपसरण / डाइवर्जेंस", ["div operator", "vector field flux"], True),
    ("curl", "कर्ल / घूर्णन", ["rotor", "vector curl"], True),
    ("laplacian", "लाप्लासियन", ["laplace operator", "del squared"], True),
    ("hessian", "हेसियन", ["hessian matrix", "second derivative matrix"], True),
    ("jacobian", "जैकबियन", ["jacobian matrix", "multivariate derivative tensor"], True),
    ("taylor-series", "टेलर श्रृंखला", ["taylor polynomial", "maclaurin series"], True),
    ("power-series", "घात श्रृंखला", ["radius of convergence", "analytic function"], False),
    ("fourier-transform", "फूरियर रूपांतरण", ["fourier series", "fft", "frequency analysis"], True),
    ("laplace-transform", "लाप्लास रूपांतरण", ["s-domain transform", "differential equation transform"], True),
    ("complex-analysis", "जटिल विश्लेषण", ["holomorphic function", "cauchy-riemann equations"], True),
    ("holomorphic", "होलोमोर्फिक", ["analytic complex function", "complex differentiable"], True),
    ("contour-integral", "कंटूर समाकलन", ["cauchy integral theorem", "residue calculus"], True),
    ("residue-theorem", "अवशेष प्रमेय", ["cauchy residue theorem", "pole analysis"], True),
    ("riemann-integral", "रीमैन समाकलन", ["riemann sum", "partition integration"], True),
    ("lebesgue-integral", "लेबेस्ग समाकलन", ["measure-theoretic integration", "lebesgue measure"], True),
    ("measure-theory", "माप सिद्धांत", ["sigma-algebra", "measurable space"], True),
    ("sigma-algebra", "सिग्मा-बीजगणित", ["borel sigma algebra", "measurable sets"], True),
    ("topology", "टोपोलॉजी / संस्थिति विज्ञान", ["topological space", "open and closed sets"], True),
    ("compactness", "सघनता / कॉम्पेक्टनेस", ["compact set", "heine-borel theorem"], True),
    ("connectedness", "संबद्धता", ["connected topological space", "path connected"], False),
    ("homeomorphism", "होमियोमॉर्फिज्म", ["topological equivalence", "continuous bijection"], True),
    ("metric-space", "दूरीक अंतरिक्ष / मेट्रिक स्पेस", ["metric function", "triangle inequality distance"], True),
    ("cauchy-sequence", "कॉची अनुक्रम", ["completeness", "convergent sequence"], True),
    ("hilbert-space", "हिल्बर्ट अंतरिक्ष", ["complete inner product space", "infinite dimensional vector space"], True),
    ("banach-space", "बानाख अंतरिक्ष", ["complete normed space", "functional analysis"], True),
    ("group-theory", "समूह सिद्धांत", ["algebraic group", "abelian group", "symmetry group"], True),
    ("abelian-group", "एबेलियन समूह", ["commutative group", "additive group"], True),
    ("subgroup", "उपसमूह", ["normal subgroup", "lagrange theorem on groups"], False),
    ("homomorphism", "होमोमोर्फिज्म / समाकारिता", ["group homomorphism", "isomorphism"], True),
    ("isomorphism", "आइसोमोर्फिज्म / तुल्यकारिता", ["bijective homomorphism", "structural equivalence"], True),
    ("ring-theory", "वलय सिद्धांत", ["commutative ring", "integral domain"], True),
    ("field-theory", "क्षेत्र सिद्धांत", ["galois field", "algebraic field extension"], True),
    ("prime-number", "अभाज्य संख्या", ["prime factorization", "sieve of eratosthenes"], False),
    ("gcd", "महत्तम समापवर्तक", ["greatest common divisor", "euclidean algorithm"], False),
    ("modular-arithmetic", "मॉड्यूलर अंकगणित", ["modulo n", "congruence relation"], False),
    ("fermat-little-theorem", "फर्मेट का छोटा प्रमेय", ["modular exponentiation theorem", "primality"], True),
    ("euler-totient", "यूलर टोटिएंट फलन", ["phi function", "totient theorem"], True),
    ("combinatorics", "क्रमपरिवर्तन और संयोजन", ["permutations", "combinations", "binomial theorem"], False),
    ("permutation", "क्रमपरिवर्तन", ["ordered arrangement", "npr"], False),
    ("combination", "संयोजन", ["selection without order", "ncr"], False),
    ("binomial-theorem", "द्विपद प्रमेय", ["binomial expansion", "pascal triangle"], True),
    ("pigeonhole-principle", "कबूतर का सिद्धांत", ["dirichlet box principle", "combinatorial existence"], False),
    ("graph-theory", "ग्राफ सिद्धांत", ["eulerian path", "hamiltonian cycle"], False),
    ("differential-equation", "अवकल समीकरण", ["ode", "ordinary differential equation"], True),
    ("partial-differential-equation", "आंशिक अवकल समीकरण", ["pde", "heat equation", "wave equation"], True),
    ("boundary-value-problem", "सीमा मान समस्या", ["dirichlet boundary", "neumann boundary"], False),
    ("initial-value-problem", "प्रारंभिक मान समस्या", ["cauchy problem", "ivp"], False),
    ("euler-method", "यूलर विधि", ["numerical integration ode", "forward euler"], True),
    ("runge-kutta", "रुंगे-कुट्टा", ["rk4", "fourth-order ode solver"], True),
    ("convex-optimization", "उत्तल अनुकूलन", ["convex programming", "convex set", "convex function"], True),
    ("convex-hull", "उत्तल आवरण", ["minimal convex set", "bounding polygon"], False),
    ("lagrange-multiplier", "लाग्रेंज गुणक", ["constrained optimization", "lagrangian duality"], True),
    ("kkt-conditions", "केकेटी शर्तें", ["karush-kuhn-tucker", "nonlinear optimization optimality"], True),
    ("linear-programming", "रैखिक प्रोग्रामिंग", ["simplex method", "dual linear program"], True),
    ("simplex-algorithm", "सिम्प्लेक्स एल्गोरिदम", ["dantzig simplex", "polytope vertex search"], True),
    ("expected-value", "अपेक्षित मान / प्रत्याशा", ["mathematical expectation", "mean of distribution"], False),
    ("standard-deviation", "मानक विचलन", ["sigma", "square root of variance"], False),
    ("covariance", "सहप्रसरण / सह-विचरण", ["covariance matrix", "joint variability"], False),
    ("correlation", "सहसंबंध", ["pearson correlation coefficient", "r value"], False),
    ("normal-distribution", "सामान्य वितरण", ["gaussian distribution", "bell curve"], True),
    ("binomial-distribution", "द्विपद वितरण", ["bernoulli trials", "discrete binomial"], True),
    ("poisson-distribution", "पॉइसन वितरण", ["poisson process", "rare event count"], True),
    ("exponential-distribution", "घातीय वितरण", ["memoryless distribution", "waiting time"], True),
    ("central-limit-theorem", "केंद्रीय सीमा प्रमेय", ["clt", "asymptotic normality"], True),
    ("law-of-large-numbers", "बड़ी संख्याओं का नियम", ["lln", "weak and strong law"], True),
    ("bayes-theorem", "बेयस प्रमेय", ["conditional probability formula", "posterior calculation"], True),
    ("prior-probability", "पूर्व प्रायिकता", ["prior distribution", "unconditional probability"], False),
    ("posterior-probability", "उत्तर प्रायिकता", ["posterior distribution", "bayesian inference"], False),
    ("likelihood", "संभावना / संभावना फलन", ["likelihood function", "maximum likelihood estimation"], False),
    ("maximum-likelihood", "अधिकतम संभावना", ["mle", "parameter estimation"], True),
    ("hypothesis-testing", "परिकल्पना परीक्षण", ["null hypothesis", "alternative hypothesis"], False),
    ("p-value", "पी-मान", ["statistical significance level", "alpha threshold"], True),
    ("confidence-interval", "विश्वास अंतराल", ["margin of error", "95% confidence interval"], False),
    ("markov-chain", "मार्कोव श्रृंखला", ["markov process", "transition matrix"], True),
    ("stochastic-process", "स्टोकेस्टिक प्रक्रिया", ["random process", "martingale"], False),
    ("monte-carlo", "मोंटे कार्लो", ["monte carlo simulation", "random sampling integration"], True),
    ("mcmc", "एमसीएमसी", ["markov chain monte carlo", "metropolis-hastings"], True),
    ("manifold", "मैनिफोल्ड / बहुरूप", ["riemannian manifold", "differential manifold"], True),
    ("tangent-space", "स्पर्शरेखा अंतरिक्ष", ["tangent bundle", "tangent vector"], False),
    ("curvature", "वक्रता / कर्वेचर", ["riemann curvature tensor", "gaussian curvature"], False),
    ("geodesic", "जियोडेसिक / न्यूनतम पथ", ["geodesic curve", "shortest path on surface"], True),
    ("affine-space", "एफाइन अंतरिक्ष", ["affine geometry", "affine combination"], False),
    ("simplex", "सिम्प्लेक्स", ["n-dimensional tetrahedron", "barycentric coordinates"], False),
    ("hyperplane", "हाइपरप्लेन", ["separating hyperplane", "affine subspace codimension 1"], False),
    ("euclidean-distance", "यूक्लिडियन दूरी", ["l2 distance", "pythagorean metric"], False),
    ("manhattan-distance", "मैनहट्टन दूरी", ["l1 distance", "city block metric"], False),
    ("minkowski-distance", "मिंकोवस्की दूरी", ["generalized lp metric", "p-norm distance"], False),
    ("hamming-distance", "हैमिंग दूरी", ["binary string difference", "bit errors"], False),
    ("jaccard-index", "जैकार्ड सूचकांक", ["jaccard similarity", "intersection over union"], True),
    ("kl-divergence", "केएल अपसरण", ["kullback-leibler divergence", "relative entropy"], True),
    ("entropy", "एन्ट्रॉपी / अव्यवस्था", ["shannon entropy", "information entropy"], True),
    ("mutual-information", "पारस्परिक जानकारी", ["information gain", "joint entropy reduction"], True),
    ("cosine", "कोसाइन", ["trigonometric cosine", "cos angle"], False),
    ("sine", "साइन", ["trigonometric sine", "sin angle"], False),
    ("tangent", "टेंजेंट / स्पर्शरेखा", ["tan function", "derivative tangent line"], False),
    ("hypotenuse", "कर्ण", ["pythagorean theorem hypotenuse", "right angle triangle"], False),
    ("pythagoras-theorem", "पाइथागोरस प्रमेय", ["right angled triangle rule", "a^2 + b^2 = c^2"], True),
    ("arithmetic-progression", "अंकगणितीय प्रगति", ["ap series", "common difference"], False),
    ("geometric-progression", "ज्यामितीय प्रगति", ["gp series", "common ratio"], False),
    ("fibonacci-sequence", "फाइबोनैचि अनुक्रम", ["golden ratio sequence", "recurrence relation"], True),
    ("golden-ratio", "स्वर्ण अनुपात", ["phi", "1.618 golden proportion"], True),
    ("asymptote", "अनंतस्पर्शी", ["vertical asymptote", "horizontal asymptote curve"], False),
    ("convexity", "उत्तलता", ["jensen inequality", "epigraph"], False),
    ("concavity", "अवतलता", ["strictly concave function", "negative second derivative"], False),
    ("inflection-point", "परिवर्तन बिंदु / मोड़", ["second derivative zero change", "curvature change"], False),
    ("extrema", "चरम मान / एक्सट्रीमा", ["local maximum", "global minimum"], False),
    ("optimization", "अनुकूलन", ["mathematical optimization", "extremization"], False),
    ("calculus", "कैलकुलस / कलन", ["differential and integral calculus", "analysis"], True),
    ("real-analysis", "वास्तविक विश्लेषण", ["lebesgue measure", "bolzano-weierstrass theorem"], True),
    ("complex-number", "मिश्र संख्या / जटिल संख्या", ["imaginary unit i", "argand plane"], False),
    ("polar-coordinates", "ध्रुवीय निर्देशांक", ["radius and angle", "r-theta mapping"], False),
    ("cartesian-coordinates", "कार्तीय निर्देशांक", ["orthogonal x-y-z coordinate system", "euclidean space"], False),
]

def make_term_dict(terms_list):
    """Converts a list of tuples to formatted term objects."""
    records = []
    for term, hi, aliases, protected in terms_list:
        records.append({
            "term": term,
            "hindi": hi,
            "aliases": aliases,
            "protected": protected,
        })
    return records


def build_and_save():
    domains = {
        "deep_learning": DL_TERMS,
        "computer_science": CS_TERMS,
        "mathematics": MATH_TERMS,
    }

    for dom, terms_list in domains.items():
        records = make_term_dict(terms_list)
        path = TERMINOLOGY_DIR / f"{dom}.json"
        payload = {
            "domain": dom,
            "version": "2.0",
            "term_count": len(records),
            "terms": records,
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        print(f"Wrote {len(records)} terms to {path}")


if __name__ == "__main__":
    build_and_save()
